### ISSUE TITLE
user adding birth date not working correctly

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-5.0#62] opened 2018-09-22 23:05 UTC
![2018-09-22_18-02-58](https://user-images.githubusercontent.com/17736688/45922476-60014a00-be92-11e8-89fe-903e96f345fa.gif)

**Comment by MacWarrior** [comment] 2018-09-23 12:42
Hi, 

Can you give a bit more informations ?
As I see, everything is working fine ? (Maybe a missing message to validate the data saving ?)

**Comment by spirogg** [comment] 2018-09-23 15:16
No the date is m-d-Y 

It switches to d-m-Y when I select date. And sometimes it switches back to 2018 today's date. If select 2000 any month any day.

**Comment by MacWarrior** [comment] 2018-09-24 07:58
Ok, got it !
The problem is related to the saving (it exchange day and month) ; working on it

**Comment by MacWarrior** [comment] 2018-09-24 08:10
Fixed in this commit : 11b30af78ab540fae3b73f3edade570504d6edce

**Closed by MacWarrior** 2018-09-24 08:10 UTC
Labels: bug
